apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rw-markable
  namespace: flux-system
spec:
  path: "./kubernetes/apps/rw-markable/app"
  dependsOn:
    - name: tailscale
  postBuild:
    substitute:
      APP_NAME: rw-markable
      APP_NAMESPACE: apps
      PVC_CAPACITY: "32Gi"

