apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpn-diagnose
  namespace: flux-system
spec:
  path: "./kubernetes/apps/vpn-diagnose/app"
  dependsOn:
    - name: vpn-gateway
