apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  path: "./kubernetes/apps/grafana/app"
  dependsOn:
    - name: traefik
    - name: prometheus-stack
    - name: influxdb2
    - name: tailscale
  postBuild:
    substitute:
      APP_NAME: grafana
      APP_NAMESPACE: monitoring
