apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: donetick
  namespace: flux-system
spec:
  path: "./kubernetes/apps/donetick/app"
  dependsOn:
    - name: tailscale
  postBuild:
    substitute:
      APP_NAME: donetick
      APP_NAMESPACE: apps
      PVC_CAPACITY: "16Gi"

