apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mail-archiver-db
  namespace: flux-system
spec:
  path: "./kubernetes/templates/postgres"
  wait: true
  postBuild:
    substitute:
      APP_NAME: mail-archiver
      APP_NAMESPACE: apps
      POSTGRES_DATABASE: "MailArchiver"
      POSTGRES_MAJOR: "16"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mail-archiver
  namespace: flux-system
spec:
  path: "./kubernetes/apps/mail-archiver/app"
  wait: true
  dependsOn:
    - name: mail-archiver-db
  postBuild:
    substitute:
      APP_NAME: mail-archiver
      APP_NAMESPACE: apps
      PVC_CAPACITY: "4Gi"
      POSTGRES_DATABASE: "MailArchiver"
