apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/apps.yaml
  - resources/backup.yaml
  - resources/dashboard.yaml
  - resources/database.yaml
  - resources/home-automation.yaml
  - resources/kubevirt.yaml
  - resources/minio-operator.yaml
  - resources/monitoring.yaml
  - resources/networking.yaml
  - resources/notification.yaml
  - resources/policy.yaml
  - resources/storage.yaml
  - resources/system.yaml
  - resources/vpn-apps.yaml
  - resources/vpn-gateway.yaml
  - resources/security.yaml
