apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-puller
  namespace: flux-system
spec:
  path: "./kubernetes/apps/image-puller/app"
  postBuild:
    substitute:
      APP_NAME: image-puller
      APP_NAMESPACE: system

