apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: influxdb2
  namespace: flux-system
spec:
  path: "./kubernetes/apps/influxdb2/app"
  wait: true
  dependsOn:
    - name: volsync
  postBuild:
    substitute:
      APP_NAME: influxdb2
      APP_NAMESPACE: monitoring
      PVC_CAPACITY: "32Gi"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: influxdb2-extensions
  namespace: flux-system
spec:
  path: "./kubernetes/apps/influxdb2/extensions"
  dependsOn:
    - name: influxdb2
  postBuild:
    substitute:
      APP_NAME: influxdb2-extensions
      APP_NAMESPACE: monitoring
