apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lubelogger
  namespace: flux-system
spec:
  path: "./kubernetes/apps/lubelogger/app"
  dependsOn:
    - name: tailscale
  postBuild:
    substitute:
      APP_NAME: lubelogger
      APP_NAMESPACE: apps
      PVC_CAPACITY: "16Gi"
