apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-cleanup
  namespace: flux-system
spec:
  path: "./kubernetes/apps/tailscale/cleanup"
  wait: true
  postBuild:
    substitute:
      APP_NAMESPACE: networking
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  path: "./kubernetes/apps/tailscale/operator"
  dependsOn:
    - name: tailscale-cleanup
  postBuild:
    substitute:
      APP_NAME: tailscale
      APP_NAMESPACE: networking
