---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - bitcoind/ks.yaml
 - cyberchef/ks.yaml
 - email2signal/ks.yaml
 - esp-dashboard/ks.yaml
 - excalidraw/ks.yaml
 - gitea-runner/ks.yaml
 - gitea/ks.yaml
 - grafana/ks.yaml
 - home-assistant/ks.yaml
 - image-puller/ks.yaml
 - immich/ks.yaml
 - influxdb2/ks.yaml
 - it-tools/ks.yaml 
 - jdownloader/ks.yaml
 - jellyfin/ks.yaml
 - jellyseerr/ks.yaml
 - kubetail/ks.yaml
 - linkwarden/ks.yaml
 - lubelogger/ks.yaml
 - mail-archiver/ks.yaml
 - manyfold/ks.yaml
 - mealie/ks.yaml
 - miniflux/ks.yaml
 - monerod/ks.yaml
 - mosquitto/ks.yaml
 - ncps/ks.yaml
 - netboot-xyz/ks.yaml
 - network-share/ks.yaml
 - nodered/ks.yaml
 - nzbget/ks.yaml
 - omni-tools/ks.yaml
 - open-webui/ks.yaml
 - paperless-ai/ks.yaml
 - paperless/ks.yaml
 - pgadmin/ks.yaml
 - qbittorrent/ks.yaml
 - readeck/ks.yaml
 - scrutiny/ks.yaml
 - searxng/ks.yaml
 - solaredge/ks.yaml
 - stirling-pdf/ks.yaml 
 - syncify/ks.yaml
 - syncthing/ks.yaml
 - tailscale/ks.yaml
 - telegraf/ks.yaml
 - unifi/ks.yaml
 - uptime-kuma/ks.yaml
 - vault/ks.yaml
 - vaultwarden/ks.yaml
 - vikunja/ks.yaml
 - vpn-diagnose/ks.yaml
 - vpn-gateway/ks.yaml
 - watcharr/ks.yaml
 - wg-easy/ks.yaml
 - wiki/ks.yaml
 - zigbee2mqtt/ks.yaml
