---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube-charts
  namespace: flux-system
spec:
  interval: 24h
  timeout: 3m
  url: https://backube.github.io/helm-charts/
