---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor-container-webhook-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://indeedeng.github.io/harbor-container-webhook/
  timeout: 3m
