# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: influxdata-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.influxdata.com/
  timeout: 3m
