apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn-apps
resources:
  - ../../../templates/volsync-pvc
  - app.yaml
configMapGenerator:
  - name: nzbget-scripts
    files:
      - scripts/GetPw.py
      - scripts/DeleteSamples.py
generatorOptions:
  disableNameSuffixHash: true
